-- order matters, plenary is required by other packages to needs to be loaded first
require('plugins.plenary')

require('plugins.telescope')
require('plugins.friendly_snippets')
require('plugins.lua_snip')
require('plugins.blink_cmp')
require('plugins.harpoon')
require('plugins.cloak')
require('plugins.colorschemes')
require('plugins.fidget')
require('plugins.gitsigns')
require('plugins.indent_blankline')
require('plugins.undotree')
require('plugins.trouble')
require('plugins.todo_comments')
